### ISSUE TITLE
example DMD throws errors - kwargs instead of args?

### ISSUE THREAD

**Issue by shervinsahba** [andgoldschmidt/DMD#1]
Yo, the DMD cells throw errors in example.ipynb. 

Seems like you might have updated your DMD.py code so that the DMD class takes kwargs, but example.ipynb has the classes using args.

```
-----------------------------------------
TypeErrorTraceback (most recent call last)
<ipython-input-20-32da38813800> in <module>
      6 
      7 # 1 - Regular DMD
----> 8 dmd = DMD.DMD(data, ts)
      9 axes[0].plot(ts, dmd.predict(ts)[0].real, c=color[0])
     10 axes[0].plot(dmd.orig_timesteps, dmd.X1[0], ls='--', c=color[2])

TypeError: __init__() takes 1 positional argument but 3 were given
```

```
class DMD:
    def __init__(self, **kwargs):
...
```

**Comment by shervinsahba** [comment]
Yeah, that seemed like all it was.
You probably know, but the DMDc you have still uses positional args, but DMD was moved to kwargs** at some point.

**Comment by andgoldschmidt** [comment]
Yeah I didn't push the local change..not sure the best way to do it yet.
Can't decide if an interface is worth it or what I want. I should change to
an args, kwargs so it doesn't break old code though

**Comment by andgoldschmidt** [comment]
Updated, closed.
