### ISSUE TITLE
Examples.ipynb threshold issue

### ISSUE THREAD

**Issue by benoitpaillard** [andgoldschmidt/DMD#2]
Hi all, in cell [6] of Examples.ipynb, I do not get the expected reconstruction with the default values. It looks like the class DMD was updated somehow, so in order for the example to run I think you need to change:

`dmd = DMD.DMD.from_full(delay_embed(data, shift), ts[shift:], threshold=10)`

by

`dmd = DMD.DMD.from_full(delay_embed(data, shift), ts[shift:], threshold=0.1)`

(Also the help from DMD class mentions 'number' or 'percent' while the code takes 'count')

Thanks for the great tool !

**Comment by andgoldschmidt** [comment]
Thanks for noting this. The DMD code now includes different types of thresholding, and I've updated the examples to match.
